---
AllCops:
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Exclude:
    - spec/**/*_spec.rb
