#!/usr/bin/env ruby

require "open3"

ARGS = "-C sweeper.io -m developers@sweeper.io -I mit".freeze

def run_generator(type, name)
  command = "chef generate #{type} #{name} #{ARGS}"
  output, err, status = Open3.capture3(command)
  puts output
  puts err if status != 0
end

def usage
  puts "USAGE:"
  puts "flay cookbook NAME"
  puts "flay recipe NAME"
  exit 1
end

type, name = ARGV
usage if ARGV.size != 2
usage if type.nil? || name.nil?

case type
when "cookbook" then run_generator("cookbook", name)
when "recipe" then run_generator("recipe", name)
else
  usage
end
